Exiv2: Action::Rename Class Reference
Action::Rename Class Reference
Rename a file to its metadate creation timestamp, in the specified format.
#include <actions.hpp>
Public Types
typedef std::auto_ptr< Rename > AutoPtr
Public Types inherited from Action::Task
typedef std::auto_ptr< Task > AutoPtr
Shortcut for an auto pointer.
Public Member Functions
virtual int run (const std::string &path)
Application interface to perform a task.
AutoPtr clone () const
Public Member Functions inherited from Action::Task
virtual ~Task ()
Virtual destructor.
AutoPtr clone () const
Virtual copy construction.
Detailed Description
Rename a file to its metadate creation timestamp, in the specified format.
Member Function Documentation
int Action::Rename::run (const std::string & path) virtual
Application interface to perform a task.
Parameters
path Path of the file to process.
Returns
0 if successful.
Implements Action::Task.
References Exiv2::ExifData::empty(), Exiv2::ExifData::end(), Exiv2::fileExists(), Exiv2::ExifData::findKey(), Params::instance(), Exiv2::ImageFactory::open(), and Exiv2::string.
The documentation for this class was generated from the following files:
actions.hpp
actions.cpp