Exiv2: Action::Erase Class Reference
Action::Erase Class Reference
Erase the entire exif data or only the thumbnail section.
#include <actions.hpp>
Public Types
typedef std::auto_ptr< Erase > AutoPtr
Public Types inherited from Action::Task
typedef std::auto_ptr< Task > AutoPtr
Shortcut for an auto pointer.
Public Member Functions
virtual int run (const std::string &path)
Application interface to perform a task.
AutoPtr clone () const
int eraseThumbnail (Exiv2::Image *image) const
Delete the thumbnail image, incl IFD1 metadata from the file.
int eraseExifData (Exiv2::Image *image) const
Erase the complete Exif data block from the file.
int eraseIptcData (Exiv2::Image *image) const
Erase all Iptc data from the file.
int eraseComment (Exiv2::Image *image) const
Erase Jpeg comment from the file.
int eraseXmpData (Exiv2::Image *image) const
Erase XMP packet from the file.
Public Member Functions inherited from Action::Task
virtual ~Task ()
Virtual destructor.
AutoPtr clone () const
Virtual copy construction.
Detailed Description
Erase the entire exif data or only the thumbnail section.
Member Function Documentation
int Action::Erase::run (const std::string & path) virtual
Application interface to perform a task.
Parameters
path Path of the file to process.
Returns
0 if successful.
Implements Action::Task.
References eraseComment(), eraseExifData(), eraseIptcData(), eraseThumbnail(), eraseXmpData(), Exiv2::fileExists(), Params::instance(), Exiv2::ImageFactory::open(), and Params::target_.
The documentation for this class was generated from the following files:
actions.hpp
actions.cpp