Exiv2: Action::Insert Class Reference
Action::Insert Class Reference
Insert the Exif data from corresponding *.exv files.
#include <actions.hpp>
Public Types
typedef std::auto_ptr< Insert > AutoPtr
Public Types inherited from Action::Task
typedef std::auto_ptr< Task > AutoPtr
Shortcut for an auto pointer.
Public Member Functions
virtual int run (const std::string &path)
Application interface to perform a task.
AutoPtr clone () const
int insertThumbnail (const std::string &path) const
Insert a Jpeg thumbnail image from a file into file path. The filename of the thumbnail is expected to be the image filename (path) minus its suffix plus "-thumb.jpg".
int insertXmpPacket (const std::string &path) const
Insert an XMP packet from a file into file path. The filename of the XMP packet is expected to be the image filename (path) minus its suffix plus ".xmp".
Public Member Functions inherited from Action::Task
virtual ~Task ()
Virtual destructor.
AutoPtr clone () const
Virtual copy construction.
Detailed Description
Insert the Exif data from corresponding *.exv files.
Member Function Documentation
int Action::Insert::run (const std::string & path) virtual
Application interface to perform a task.
Parameters
path Path of the file to process.
Returns
0 if successful.
Implements Action::Task.
References Exiv2::fileExists(), insertThumbnail(), insertXmpPacket(), Params::instance(), Exiv2::ImageType::none, Exiv2::string, Params::suffix_, and Params::target_.
The documentation for this class was generated from the following files:
actions.hpp
actions.cpp