Exiv2: Action::Modify Class Reference
Action::Modify Class Reference
Modify the Exif data according to the commands in the modification table.
#include <actions.hpp>
Public Types
typedef std::auto_ptr< Modify > AutoPtr
Public Types inherited from Action::Task
typedef std::auto_ptr< Task > AutoPtr
Shortcut for an auto pointer.
Public Member Functions
virtual int run (const std::string &path)
Application interface to perform a task.
AutoPtr clone () const
Public Member Functions inherited from Action::Task
virtual ~Task ()
Virtual destructor.
AutoPtr clone () const
Virtual copy construction.
Static Public Member Functions
static int applyCommands (Exiv2::Image *pImage)
Apply modification commands to the pImage, return 0 if successful.
Detailed Description
Modify the Exif data according to the commands in the modification table.
Member Function Documentation
int Action::Modify::run (const std::string & path) virtual
Application interface to perform a task.
Parameters
path Path of the file to process.
Returns
0 if successful.
Implements Action::Task.
References applyCommands(), Exiv2::fileExists(), Params::instance(), and Exiv2::ImageFactory::open().
The documentation for this class was generated from the following files:
actions.hpp
actions.cpp