Exiv2: Exiv2::ExifKey::Impl Struct Reference
Exiv2::ExifKey::Impl Struct Reference
Internal Pimpl structure with private members and data of class ExifKey.
Public Member Functions
Creators
Impl ()
Default constructor.
Manipulators
void makeKey (uint16_t tag, IfdId ifdId, const TagInfo *tagInfo)
Set the key corresponding to the tag, ifdId and tagInfo. The key is of the form 'Exif.groupName.tagName'.
void decomposeKey (const std::string &key)
Parse and convert the key string into tag and IFD Id. Updates data members if the string can be decomposed, or throws Error .
Accessors
std::string tagName () const
Return the name of the tag.
Public Attributes
const TagInfo * tagInfo_
Tag info.
uint16_t tag_
Tag value.
IfdId ifdId_
The IFD associated with this tag.
int idx_
Unique id of the Exif key in the image.
std::string groupName_
The group name.
std::string key_
Key
Static Public Attributes
static const char * familyName_ = "Exif"
"Exif"
Detailed Description
Internal Pimpl structure with private members and data of class ExifKey.
Member Function Documentation
void Exiv2::ExifKey::Impl::decomposeKey (const std::string & key)
Parse and convert the key string into tag and IFD Id. Updates data members if the string can be decomposed, or throws Error .
Exceptions
Error if the key cannot be decomposed.
References Exiv2::ExifKey::familyName(), Exiv2::Internal::groupId(), Exiv2::ExifKey::groupName(), Exiv2::ExifKey::ifdId(), Exiv2::Internal::isExifIfd(), Exiv2::Internal::isMakerIfd(), Exiv2::string, Exiv2::ExifKey::tag(), Exiv2::Internal::tagInfo(), Exiv2::ExifKey::tagName(), and Exiv2::Internal::tagNumber().
Referenced by Exiv2::ExifKey::ExifKey().
The documentation for this struct was generated from the following file:
tags.cpp