// Robin Mills (C) Copyright 1993
extern "C" void FAR PASCAL _export Robin (int n) ;
extern "C" void FAR PASCAL _export Alan  (int n) ;

# define IDD_Diction         99

# define IDD_DictionBox     100
# define IDD_DictionTime    101
# define IDD_DictionDate    102
# define IDD_DictionText    103
# define IDD_DictionEdit    104
# define IDD_DictionOptions 105
# define IDD_DictionMenu    106

# define IDD_OptionLanguage 200
# define IDD_Option1        201
# define IDD_Option2        202
# define IDD_Option3        203
# define IDD_Option4        204
# define IDD_OptionTop      205


