/* @(#)CM_VerSion xdpsops.h 3010 1.3 19928.eco sum= 06670 3010.102 */
/* @(#)CM_VerSion xdpsops.h 2017 1.2 17334.eco sum= 64442 2017.011 */
/* @(#)CM_VerSion xdpsops.h 2015 1.3 09954.eco sum= 20864 */
/* @(#)CM_VerSion xdpsops.h 2014 1.2 08466.eco sum= 39725 */
/* @(#)CM_VerSion xdpsops.h 2013 1.2 06671.eco sum= 05454 */
/*
  xdpsops.h

(c) Copyright 1993 Adobe Systems Incorporated.
All rights reserved.  All information contained herein is the property
of Adobe Systems Incorporated or its Licensors, and are protected trade
secrets and copyrights, and may be covered by U.S. and foreign patents
or patents pending and/or mask works.  Any reproduction or dissemination
of any portion of this document or of software or other works derived
from it is strictly forbidden unless prior written permission is
obtained from Adobe Systems Incorporated.

Patents Pending

PostScript and Display PostScript are trademarks of Adobe Systems
Incorporated which may be registered in certain jurisdictions.

*/

#ifndef _XDPSOPS_H_
#define _XDPSOPS_H_

/*
*******************************************************************************
*                                                                             *
*  File: xdpsops.h                                                            *
*                                                                             *
*******************************************************************************
*/

/*-----------------------------------------*/
/* Public interfaces from PostScript world */
/*-----------------------------------------*/

#include PACKAGE_SPECS
#include ENVIRONMENT
#include PUBLICTYPES

extern void XDPS_RegisterXcustomOps (void);

#endif /* _XDPDOPS_H_ */
