#!/bin/bash

##
# build ToWebPlugin.jar
##

# static data
plugins="$HOME/Library/Application Support/eTeks/Sweet Home 3D/plugins/"
foo=foo
jar=ToWebPlugin.jar

del      "$plugins/templates"
mkdir -p "$plugins/templates"

cp *.jar "$plugins"
cd       "$plugins"

if [ -e "$jar" ]; then
	ls -alt "$jar"
	rm -rf  "$foo"
	mkdir   "$foo"
	for i in *.jar ; do (
	 	cd "$foo"
	 	jar xf ../$i
	) 	done
	cd "$foo"
	jar cf  "../$jar" *
	cd  ..
	rm -rf  "$foo"
	ls -alt "$jar"
else
	echo "file $jar does not exist"
fi

# That's all Folks!
##
