#!/bin/bash

##
# build ToWebPlugin.jar
##

# static data
plugins="$HOME/Library/Application Support/eTeks/Sweet Home 3D/plugins/"
foo=foo
jar=ToWebPlugin.jar
export REVISION=$(svn info . | grep ^Revision | cut -d: -f 2)
export VERSION=$(grep ^version ApplicationPlugin.properties | cut -d= -f 2)

rm -rf   "$plugins/templates"
mkdir -p "$plugins/templates"

cp *.jar "$plugins"
cd       "$plugins"

if [ -e "$jar" ]; then
	ls -alt "$jar"
	rm -rf  "$foo"
	mkdir   "$foo"
	for i in *.jar ; do (
	 	cd "$foo"
	 	jar xf ../$i
	) 	done
	cd "$foo"
	(
	   echo "Version:"   $VERSION
	   echo "Built: "    $(date)
	   echo "Revision: " $REVISION
	   echo "Host: "     $HOST
	   echo "Username: " $USER
	) > about.txt
	jar cf  "../$jar" *
	cd  ..
	rm -rf  "$foo" build.xml build .project
	ls -alt "$jar"
else
	echo "file $jar does not exist"
fi

# That's all Folks!
##
